Vagrant.configure("2") do |config|
	config.vm.network "private_network", type: "dhcp"
	
	config.vm.define "node-server" do |d|
		d.vm.box = "rockylinux/8"
		d.vm.box_version = "4.0.0"
		d.vm.provision "shell", path: "init.sh"
		d.vm.hostname = "node-server"
		d.vm.provider "virtualbox" do |v|
			v.name = "node-server"
			v.memory = 2048
		end
	end

	config.vm.define "node-client-1" do |d|
		d.vm.box = "rockylinux/8"
		d.vm.box_version = "4.0.0"
		d.vm.provision "shell", path: "init.sh"
		d.vm.hostname = "node-client-1"
		d.vm.provider "virtualbox" do |v|
			v.name = "node-client-1"
			v.memory = 1024
		end
	end
	
	config.vm.define "node-client-2" do |d|
		d.vm.box = "rockylinux/8"
		d.vm.box_version = "4.0.0"
		d.vm.provision "shell", path: "init.sh"
		d.vm.hostname = "node-client-2"
		d.vm.provider "virtualbox" do |v|
			v.name = "node-client-2"
			v.memory = 1024
		end
	end
  
end